# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'python'), ('dj', 'django'), ('ui', 'user interface'), ('ra', 'rest api')], max_length=100)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'hyderabad'), ('bang', 'banglure'), ('chn', 'chennai')], max_length=100)),
                ('shift', multiselectfield.db.fields.MultiSelectField(choices=[('mor', 'morning'), ('aft', 'afternoon'), ('evn', 'evening'), ('nig', 'night')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('feedback', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
